#include "authenticator.h"
#include "qdesktopservices.h"
#include "qoauthhttpserverreplyhandler.h"
#include "QFile"
#include "QJsonDocument"
#include "QJsonObject"
#include "QJsonArray"
#include "QNetworkReply"
#include "QIterator"
#include "mainwindow.h"
#include "qpushbutton.h"

Authenticator::Authenticator(QObject *parent) : QObject{parent}{

    this->microsoft = new QOAuth2AuthorizationCodeFlow(this);

    QFile file("../../../auth_params.json");
    //qDebug() << "exists? " << QFile::exists("../../../auth_params.json");
    QJsonDocument document;
    file.open(QIODeviceBase::ReadOnly);
    if(file.isOpen())
    {
        QByteArray json_bytes = file.readAll();
        document = QJsonDocument::fromJson(json_bytes);
        file.close();
    }

    //Parse json to get authorization parameters
    QJsonObject obj = document.object();
    QUrl authUri = obj["auth_uri"].toString();
    QString clientId = obj["client_id"].toString();
    QUrl tokenUri = obj["token_uri"].toString();
    QUrl redirectUri = obj["redirect_uri"].toString();
    quint16 port = static_cast<quint16>(redirectUri.port()); // Get the port

    //required values for authorization code request
    this->microsoft->setClientIdentifier(clientId);
    this->microsoft->setScope("User.Read Team.ReadBasic.All Channel.ReadBasic.All Files.ReadWrite.All");
    this->microsoft->setAuthorizationUrl(authUri);

    //additional required values for access token request
    this->microsoft->setAccessTokenUrl(tokenUri);

    /*
    Sets the parameter-modification function modifyParametersFunction.
    This function is used to customize the parameters sent to the server during a specified authorization stage.
    */
    this->microsoft->setModifyParametersFunction([](QAbstractOAuth::Stage stage, QMultiMap<QString, QVariant> * parameters) {
        // Percent-decode the "code" parameter
        if (stage == QAbstractOAuth::Stage::RequestingAccessToken) {
            qDebug() << "requesting access token";
            QByteArray code = parameters->value("code").toByteArray();
            parameters->replace("code", QUrl::fromPercentEncoding(code));
        }
        if (stage == QAbstractOAuth::Stage::RequestingAuthorization){
            qDebug() << "requesting autorization code";
        }
    });

    /*
    Setting reply handler
    */
    this->replyHandler = new QOAuthHttpServerReplyHandler(port, this);
    this->microsoft->setReplyHandler(replyHandler);

    /*
    authorizeWithBrowser: signal emitted when the url generated by resourceOwnerAuthorization() is ready to be used in the web browser
    resourceOwnerAuthorization(): builds the resource owner authorization URL to be used in the browser, from the values
    set above (client id, scope, authorization url).
    */
    connect(this->microsoft, &QOAuth2AuthorizationCodeFlow::authorizeWithBrowser, &QDesktopServices::openUrl);

    connect(this->microsoft, &QOAuth2AuthorizationCodeFlow::granted, [this](){
        qDebug() << "token received";
        emit loggedIn();
        //qDebug() << this->microsoft->token();
        //this->getTeamsList();
    });
}

void Authenticator::startLogin(){
    this->microsoft->grant();
}

void Authenticator::getTeamsList(QComboBox * selectTeam){
    QUrl url("https://graph.microsoft.com/v1.0/me/joinedTeams");
    QNetworkReply * reply =  this->microsoft->get(url);
    connect(reply, &QNetworkReply::finished, [this, reply, selectTeam](){
        QJsonObject reply_obj  = (QJsonDocument::fromJson(reply->readAll())).object();
        QJsonArray values = reply_obj["value"].toArray();
        qDebug() << "MY teams:";
        QMap<int, QString> ids;
        for(int p=0; p < values.size(); ++p){
            QJsonObject obj = (values.at(p)).toObject();
            QString team_name = obj["displayName"].toString();
            QString team_id = obj["id"].toString();
            selectTeam->addItem(team_name);
            ids.insert(p, team_id);
            qDebug() << "Team name: " << team_name;
            qDebug() << "Team id: " << team_id;
        }
        connect(selectTeam, &QComboBox::activated, [ids, this](int index){
            QString team_id = ids.value(index);
            qDebug() << "clicked item with index: " << index << " and id: " << team_id;
            this->getChannelsList(team_id);
        });
        //this->getChannelsList("421ef6a4-07d5-4502-9f85-0b828ac95486");
        //emit teamsListReceived();
    });
}

void Authenticator::getChannelsList(QString team_id){
    QUrl url("https://graph.microsoft.com/v1.0/teams/" + team_id + "/channels");
    QNetworkReply * reply =  this->microsoft->get(url);
    connect(reply, &QNetworkReply::finished, [this, reply, team_id](){
        QJsonObject reply_obj  = (QJsonDocument::fromJson(reply->readAll())).object();
        QJsonArray values = reply_obj["value"].toArray();
        qDebug() << "Team channels:";
        QMap<QString, QString> channels;
        for(int p=0; p < values.size(); ++p){
            QJsonObject obj = (values.at(p)).toObject();
            QString channel_name = obj["displayName"].toString();
            QString channel_id = obj["id"].toString();
            channels.insert(channel_id, channel_name);
            //this->getFilesFolder(team_id, channel_id);
            qDebug() << "Channel name: " << obj["displayName"].toString();
        }
        emit channelsListReceived(channels, team_id);
    });
}

void Authenticator::getFilesFolder(QString team_id, QString channel_id, QVBoxLayout* dockWidgetlayout){
    QUrl url("https://graph.microsoft.com/v1.0/teams/" + team_id
             + "/channels/" + channel_id + "/filesFolder?");
    QNetworkReply * reply =  this->microsoft->get(url);
    connect(reply, &QNetworkReply::finished, [this, reply, dockWidgetlayout](){
        QJsonObject reply_obj  = (QJsonDocument::fromJson(reply->readAll())).object();
        QString item_id = reply_obj["id"].toString();
        QJsonObject obj = (reply_obj["parentReference"]).toObject();
        QString drive_id = obj["driveId"].toString();
        this->getFilesFolderContent(drive_id, item_id, dockWidgetlayout);
    });
}

void Authenticator::getFilesFolderContent(QString drive_id, QString item_id, QVBoxLayout* dockWidgetlayout){
    QUrl url("https://graph.microsoft.com/v1.0/drives/" + drive_id
             + "/items/" + item_id + "/children");
    QNetworkReply * reply =  this->microsoft->get(url);
    connect(reply, &QNetworkReply::finished, [this, reply, dockWidgetlayout](){
        QJsonObject reply_obj  = (QJsonDocument::fromJson(reply->readAll())).object();
        QJsonArray values = reply_obj["value"].toArray();
        qDebug() << "My files:";
        for(int p=0; p < values.size(); ++p){
            QJsonObject obj = (values.at(p)).toObject();
            QString item_id = obj["id"].toString();
            QJsonObject obj2 = (obj["parentReference"]).toObject();
            QString site_id = obj2["siteId"].toString();
            QString file_name = obj["name"].toString();
            qDebug() << "File name: " << file_name;
            QPushButton * button = new QPushButton();
            button->setText(file_name);
            connect(button, &QPushButton::clicked, [this, site_id, item_id, dockWidgetlayout](){
                this->getFileContent(site_id, item_id);
            });
            dockWidgetlayout->addWidget(button);
        }
    });
}

void Authenticator::getFileContent(QString site_id, QString item_id){
    QUrl url("https://graph.microsoft.com/v1.0/sites/" + site_id
             +"/drive/items/"+ item_id + "/content");
    QNetworkReply * reply =  this->microsoft->get(url);
    connect(reply, &QNetworkReply::finished, [this, reply, site_id, item_id](){
        qDebug() << "File content:";
        QByteArray fileContent = reply->readAll();
        qDebug() << fileContent;
        emit fileContentReceived(fileContent, site_id, item_id);
        //this->updateFileContent(site_id, item_id);
    });
}

void Authenticator::updateFileContent(QString site_id, QString item_id, QByteArray new_text){
    QUrl url("https://graph.microsoft.com/v1.0/sites/" + site_id
             + "/drive/items/" + item_id + "/content");
    QNetworkReply * reply =  this->microsoft->put(url, new_text);
    connect(reply, &QNetworkReply::finished, [reply](){
        qDebug() << "updated text sent";
    });
}














